import { createContext, useContext, useEffect, useMemo, useState } from "react";

const AppContext = createContext(null);

const translations = {
  en: {
    brand: "Dental Automation",
    book: "Book Appointment",
    emergency: "Emergency Dental Line",
    quickBooking: "Quick Booking",
    heroTitle: "Your Smile, Our Priority",
    heroSub: "Experience medical-grade dentistry with modern technology, trusted experts, and a seamless appointment system.",
    ourServices: "Our Services",
    beforeAfter: "Before / After Gallery",
    patientTestimonials: "Patient Testimonials",
    emergencyCare: "Emergency Dental Care 24/7",
    meetDentist: "Meet The Dentist",
    viewAllDoctors: "View All Doctors",
    appointmentCalendar: "Appointment Calendar",
    contactLocation: "Contact & Location",
    adminDashboard: "Admin Dashboard",
    patientDashboard: "Patient Dashboard",
    myRecords: "My Dental Records",
    loginTitle: "Admin Login",
    signupTitle: "Patient Signup",
    login: "Admin Login",
    logout: "Logout",
    home: "Home",
    about: "About",
    services: "Services",
    doctors: "Doctors",
    contact: "Contact",
    admin: "Admin",
    dashboard: "Dashboard",
    records: "Records",
    verifiedReviews: "Verified patient feedback",
    modernCare: "Modern care",
    cleanClinic: "Clean, sterilized environment",
    contactHero: "Contact & Location",
    contactSub: "Visit our clinic or book instantly through WhatsApp.",
    loginSub: "Admin access for doctors and clinic management to review all reservations.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    loadingDoctors: "Loading doctors...",
    selectDateFirst: "Select date first",
    noTimeSlotsAvailable: "No time slots available",
    booking: "Booking...",
    bookAppointmentBtn: "Book Appointment",
    bookingSuccess: "Appointment request sent. Confirmation email is on the way.",
    bookingFailed: "Unable to book. Please try another slot.",
    premiumClinicBadge: "Premium Dental Clinic",
    statTreatments: "Successful treatments completed with documented outcomes.",
    statReviews: "Verified patient feedback and excellent service quality.",
    statIso: "Sterilization workflow and medical-grade equipment standards.",
    beforeAfterSub: "Real transformations from our smile rehabilitation cases.",
    caseLabel: "Case",
    smileOutcome: "Smile design outcome",
    emergencySub: "Severe pain, trauma, or swelling? Call immediately and we will prioritize your case.",
    callNow: "Call",
    footerTagline: "Premium, modern, and reliable dental care for your family.",
    clinicHours: "Clinic Hours",
    monSatHours: "Mon-Sat: 9:00 AM - 8:00 PM",
    sundayEmergency: "Sunday: Emergency only",
    quickLinks: "Quick Links",
    allRightsReserved: "All rights reserved.",
    appointmentCalendarSub: "Booked days are shown here so you can choose available dates faster.",
    chooseTreatment: "Choose your treatment and book in seconds.",
    doctorCareSub: "Specialists with focused expertise and compassionate care.",
    addressLine: "ABC Dental Avenue, Lahore, Pakistan",
    emergencyContact: "Emergency Contact",
    whatsappBooking: "WhatsApp Booking",
    doctorTimeSlotManagement: "Doctor Time Slot Management",
    commaSeparatedHint: "Use comma-separated values, for example: 09:00, 10:00, 11:30",
    saveSlots: "Save Slots",
    timingsUpdated: "Time slots updated.",
    timingsUpdateFailed: "Unable to update timings.",
    today: "Today",
    upcoming: "Upcoming",
    completed: "Completed",
    appointments: "Appointments",
    patient: "Patient",
    doctor: "Doctor",
    date: "Date",
    time: "Time",
    status: "Status",
    actions: "Actions",
    accept: "Accept",
    reject: "Reject",
    basicPatientRecords: "Basic Patient Records",
    service: "Service",
    aboutDescription:
      "Dental Automation combines premium aesthetics with strict clinical protocols. Our team follows sterilization standards, digital diagnostics, and personalized treatment planning for every patient.",
    medicalReliability: "Medical Reliability",
    medicalReliabilitySub: "Evidence-based procedures with transparent records and follow-up.",
    premiumExperience: "Premium Experience",
    premiumExperienceSub: "Calm interiors, smooth booking, and attentive support at every step.",
    modernTechnology: "Modern Technology",
    modernTechnologySub: "Digital X-rays, 3D planning, and precise restorative techniques.",
    duration: "Duration",
    price: "Price",
    bookNow: "Book Now",
    experience: "Experience",
    chatTitle: "Live Chat + AI FAQ",
    chatTry: "Try: clinic hours, pricing, emergency",
    yourName: "Your name",
    yourEmail: "Your email",
    askQuestion: "Ask a question",
    sendToClinic: "Send to Clinic",
    chatTypeFirst: "Please type a message first.",
    chatSendFailed: "Could not send message.",
    chatFallback: "Please leave your message and our team will reply shortly.",
    faqClinicHours: "We are open Monday to Saturday from 9:00 AM to 8:00 PM.",
    faqPricing: "Pricing depends on treatment. You can view estimates on Services page.",
    faqEmergency: "Call +92 300 1234567 immediately for urgent dental issues.",
    loadingProfile: "Loading your profile...",
    appointmentHistory: "Appointment History",
    supportMessages: "Support Messages",
    message: "Message",
    reply: "Reply",
    pending: "Pending",
    password: "Password",
    teethWhitening: "Teeth Whitening",
    teethWhiteningDesc: "Advanced whitening treatment for a naturally brighter smile.",
    rootCanalTherapy: "Root Canal Therapy",
    rootCanalTherapyDesc: "Precision care using digital diagnostics and gentle anesthesia.",
    dentalImplants: "Dental Implants",
    dentalImplantsDesc: "Long-term tooth replacement solutions with premium materials.",
    bracesAligners: "Braces & Aligners",
    bracesAlignersDesc: "Customized orthodontic plans for children and adults.",
    generalCheckup: "General Checkup",
    reservedTimeSlots: "Reserved Time Slots",
    manualReservation: "Manual Time Slot Reservation",
    selectDateAndTime: "Select Date and Time",
    reserveSlot: "Reserve Slot",
    slotReserved: "Slot has been reserved successfully.",
    slotReservationFailed: "Unable to reserve slot.",
    cancelReservation: "Cancel Reservation",
    reservationCancelled: "Reservation cancelled successfully.",
    cancelReservationFailed: "Unable to cancel reservation.",
    reason: "Reason",
  },
  ur: {
    brand: "ڈینٹل آٹومیشن",
    book: "اپائنٹمنٹ بک کریں",
    emergency: "ایمرجنسی ڈینٹل لائن",
    quickBooking: "فوری بکنگ",
    heroTitle: "آپ کی مسکراہٹ، ہماری ترجیح",
    heroSub: "جدید ٹیکنالوجی، قابل اعتماد ماہرین، اور آسان اپائنٹمنٹ سسٹم کے ساتھ اعلیٰ درجے کا ڈینٹل تجربہ۔",
    ourServices: "ہماری سروسز",
    beforeAfter: "پہلے / بعد گیلری",
    patientTestimonials: "مریضوں کی رائے",
    emergencyCare: "24/7 ایمرجنسی ڈینٹل سروس",
    meetDentist: "ڈینٹسٹ سے ملاقات",
    viewAllDoctors: "تمام ڈاکٹرز دیکھیں",
    appointmentCalendar: "اپائنٹمنٹ کیلنڈر",
    contactLocation: "رابطہ اور مقام",
    adminDashboard: "ایڈمن ڈیش بورڈ",
    patientDashboard: "مریض ڈیش بورڈ",
    myRecords: "میرے ڈینٹل ریکارڈز",
    loginTitle: "ایڈمن لاگ اِن",
    signupTitle: "مریض رجسٹریشن",
    login: "ایڈمن لاگ اِن",
    logout: "لاگ آؤٹ",
    home: "ہوم",
    about: "تعارف",
    services: "سروسز",
    doctors: "ڈاکٹرز",
    contact: "رابطہ",
    admin: "ایڈمن",
    dashboard: "ڈیش بورڈ",
    records: "ریکارڈز",
    verifiedReviews: "تصدیق شدہ مریضوں کی رائے",
    modernCare: "جدید علاج",
    cleanClinic: "صاف اور جراثیم سے پاک ماحول",
    contactHero: "رابطہ اور مقام",
    contactSub: "کلینک وزٹ کریں یا واٹس ایپ کے ذریعے فوراً بک کریں۔",
    loginSub: "ڈاکٹرز اور کلینک مینجمنٹ کے لیے تمام ریزرویشنز دیکھنے کی ایڈمن رسائی۔",
    name: "نام",
    email: "ای میل",
    phone: "فون",
    loadingDoctors: "ڈاکٹرز لوڈ ہو رہے ہیں...",
    selectDateFirst: "پہلے تاریخ منتخب کریں",
    noTimeSlotsAvailable: "وقت کے سلاٹس دستیاب نہیں",
    booking: "بک ہو رہا ہے...",
    bookAppointmentBtn: "اپائنٹمنٹ بک کریں",
    bookingSuccess: "اپائنٹمنٹ کی درخواست بھیج دی گئی ہے۔ تصدیقی ای میل جلد موصول ہوگی۔",
    bookingFailed: "بکنگ ممکن نہیں۔ براہ کرم دوسرا سلاٹ منتخب کریں۔",
    premiumClinicBadge: "پریمیم ڈینٹل کلینک",
    statTreatments: "دستاویزی نتائج کے ساتھ کامیاب علاج مکمل کیے گئے۔",
    statReviews: "تصدیق شدہ مریض رائے اور بہترین سروس معیار۔",
    statIso: "اسٹرلائزیشن طریقہ کار اور میڈیکل گریڈ آلات کے معیارات۔",
    beforeAfterSub: "ہماری اسمایل ری ہیبیلیٹیشن کیسز کی حقیقی تبدیلیاں۔",
    caseLabel: "کیس",
    smileOutcome: "مسکراہٹ ڈیزائن کا نتیجہ",
    emergencySub: "شدید درد، چوٹ یا سوجن؟ فوری کال کریں، ہم آپ کے کیس کو ترجیح دیں گے۔",
    callNow: "کال کریں",
    footerTagline: "آپ کے خاندان کے لیے پریمیم، جدید اور قابلِ اعتماد ڈینٹل نگہداشت۔",
    clinicHours: "کلینک کے اوقات",
    monSatHours: "پیر تا ہفتہ: صبح 9:00 سے رات 8:00",
    sundayEmergency: "اتوار: صرف ایمرجنسی",
    quickLinks: "فوری لنکس",
    allRightsReserved: "جملہ حقوق محفوظ ہیں۔",
    appointmentCalendarSub: "بک شدہ دن یہاں دکھائے جاتے ہیں تاکہ آپ آسانی سے دستیاب تاریخ منتخب کر سکیں۔",
    chooseTreatment: "اپنا علاج منتخب کریں اور چند سیکنڈ میں بک کریں۔",
    doctorCareSub: "خصوصی مہارت اور ہمدردانہ دیکھ بھال رکھنے والے ماہرین۔",
    addressLine: "اے بی سی ڈینٹل ایونیو، لاہور، پاکستان",
    emergencyContact: "ایمرجنسی رابطہ",
    whatsappBooking: "واٹس ایپ بکنگ",
    doctorTimeSlotManagement: "ڈاکٹر ٹائم سلاٹ مینجمنٹ",
    commaSeparatedHint: "کاما سے الگ اقدار استعمال کریں، مثال: 09:00, 10:00, 11:30",
    saveSlots: "سلاٹس محفوظ کریں",
    timingsUpdated: "ٹائم سلاٹس اپ ڈیٹ ہو گئے۔",
    timingsUpdateFailed: "ٹائمنگز اپ ڈیٹ نہیں ہو سکیں۔",
    today: "آج",
    upcoming: "آنے والے",
    completed: "مکمل",
    appointments: "اپائنٹمنٹس",
    patient: "مریض",
    doctor: "ڈاکٹر",
    date: "تاریخ",
    time: "وقت",
    status: "حیثیت",
    actions: "اقدامات",
    accept: "منظور",
    reject: "مسترد",
    basicPatientRecords: "بنیادی مریض ریکارڈ",
    service: "سروس",
    aboutDescription:
      "ڈینٹل آٹومیشن پریمیم جمالیات کو سخت کلینیکل اصولوں کے ساتھ یکجا کرتا ہے۔ ہماری ٹیم ہر مریض کے لیے اسٹرلائزیشن معیار، ڈیجیٹل تشخیص اور ذاتی علاج منصوبہ بندی پر عمل کرتی ہے۔",
    medicalReliability: "طبی اعتبار",
    medicalReliabilitySub: "ثبوت پر مبنی طریقہ علاج، شفاف ریکارڈ اور فالو اپ کے ساتھ۔",
    premiumExperience: "پریمیم تجربہ",
    premiumExperienceSub: "پرسکون ماحول، آسان بکنگ اور ہر مرحلے پر توجہ رکھنے والی سپورٹ۔",
    modernTechnology: "جدید ٹیکنالوجی",
    modernTechnologySub: "ڈیجیٹل ایکس رے، تھری ڈی پلاننگ اور درست بحالی تکنیکیں۔",
    duration: "دورانیہ",
    price: "قیمت",
    bookNow: "ابھی بک کریں",
    experience: "تجربہ",
    chatTitle: "لائیو چیٹ + اے آئی سوالات",
    chatTry: "آزمائیں: کلینک اوقات، قیمت، ایمرجنسی",
    yourName: "آپ کا نام",
    yourEmail: "آپ کی ای میل",
    askQuestion: "سوال پوچھیں",
    sendToClinic: "کلینک کو بھیجیں",
    chatTypeFirst: "براہ کرم پہلے پیغام لکھیں۔",
    chatSendFailed: "پیغام نہیں بھیجا جا سکا۔",
    chatFallback: "براہ کرم اپنا پیغام چھوڑیں، ہماری ٹیم جلد جواب دے گی۔",
    faqClinicHours: "ہم پیر سے ہفتہ صبح 9:00 سے رات 8:00 تک کھلے ہوتے ہیں۔",
    faqPricing: "قیمت علاج کے مطابق ہوتی ہے۔ اندازے سروسز صفحہ پر دیکھ سکتے ہیں۔",
    faqEmergency: "فوری ڈینٹل مسئلے کی صورت میں فوراً +92 300 1234567 پر کال کریں۔",
    loadingProfile: "آپ کی پروفائل لوڈ ہو رہی ہے...",
    appointmentHistory: "اپائنٹمنٹ ہسٹری",
    supportMessages: "سپورٹ پیغامات",
    message: "پیغام",
    reply: "جواب",
    pending: "زیرِ التوا",
    password: "پاس ورڈ",
    teethWhitening: "دانتوں کی سفیدی",
    teethWhiteningDesc: "قدرتی طور پر روشن مسکراہٹ کے لیے جدید سفیدی کا علاج۔",
    rootCanalTherapy: "روٹ کینال تھراپی",
    rootCanalTherapyDesc: "ڈیجیٹل تشخیص اور نرم اینستھیزیا کے ساتھ درست علاج۔",
    dentalImplants: "ڈینٹل امپلانٹس",
    dentalImplantsDesc: "اعلیٰ معیار کے مواد کے ساتھ دانتوں کی طویل مدتی تبدیلی کا حل۔",
    bracesAligners: "بریسز اور الائنرز",
    bracesAlignersDesc: "بچوں اور بڑوں کے لیے حسبِ ضرورت آرتھوڈانٹک منصوبے۔",
    generalCheckup: "عام چیک اپ",
    reservedTimeSlots: "محفوظ شدہ وقت کے سلاٹس",
    manualReservation: "دستی وقت کی سلاٹ ریزرویشن",
    selectDateAndTime: "تاریخ اور وقت منتخب کریں",
    reserveSlot: "سلاٹ ریزرو کریں",
    slotReserved: "سلاٹ کامیابی سے محفوظ ہو گیا۔",
    slotReservationFailed: "سلاٹ ریزرو نہیں کیا جا سکا۔",
    cancelReservation: "ریزرویشن منسوخ کریں",
    reservationCancelled: "ریزرویشن کامیابی سے منسوخ کر دی گئی۔",
    cancelReservationFailed: "ریزرویشن منسوخ نہیں کی جا سکی۔",
    reason: "وجہ",
  },
};

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(localStorage.getItem("theme") || "light");
  const [language, setLanguage] = useState(localStorage.getItem("language") || "en");
  const [user, setUser] = useState(() => {
    const raw = localStorage.getItem("user");
    return raw ? JSON.parse(raw) : null;
  });

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language === "ur" ? "ur" : "en";
    document.documentElement.dir = language === "ur" ? "rtl" : "ltr";
  }, [language]);

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  useEffect(() => {
    if (user) {
      localStorage.setItem("user", JSON.stringify(user));
    } else {
      localStorage.removeItem("user");
    }
  }, [user]);

  const value = useMemo(
    () => ({
      theme,
      setTheme,
      language,
      setLanguage,
      t: translations[language],
      user,
      setUser,
    }),
    [theme, language, user]
  );

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used within AppProvider");
  return ctx;
}
